name: Eventually Builds

on: [push, pull_request]

jobs:
  kotlin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          ./gradlew qa

      - name: Push Coverage Result
        uses: codecov/codecov-action@v1
        with:
          flags: kotlin
