name: Eventually Builds

on: [push, pull_request]

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          ./gradlew core:qa

      - name: Push Coverage Result
        uses: codecov/codecov-action@v1
        with:
          flags: kotlin

  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          ./gradlew client-android:qa
